% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{report}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=2cm]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\renewcommand{\chaptername}{Part}
\newcommand{\fullline}{\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}}
\newcommand{\bminione}{\begin{minipage}{0.75 \textwidth}}
\newcommand{\bminitwo}{\begin{minipage}{0.25 \textwidth}}
\newcommand{\emini}{\end{minipage}}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={df},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{df}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Autogenerated data summary from dataMaid}
\author{}
\date{\vspace{-2.5em}2023-08-23 01:45:42}

\begin{document}
\maketitle

\hypertarget{data-report-overview}{%
\chapter{Data report overview}\label{data-report-overview}}

The dataset examined has the following dimensions:

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3472}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1250}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Number of observations & 32564 \\
Number of variables & 140 \\
\bottomrule()
\end{longtable}

\hypertarget{checks-performed}{%
\subsection{Checks performed}\label{checks-performed}}

The following variable checks were performed, depending on the data type
of each variable:

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.3649}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0811}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0743}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0743}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1149}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0743}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0743}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0676}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0743}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
~
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
character
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
factor
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
labelled
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
haven labelled
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
numeric
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
integer
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
logical
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Date
\end{minipage} \\
\midrule()
\endhead
Identify miscoded missing values & \(\times\) & \(\times\) & \(\times\)
& \(\times\) & \(\times\) & \(\times\) & & \(\times\) \\
Identify prefixed and suffixed whitespace & \(\times\) & \(\times\) &
\(\times\) & \(\times\) & & & & \\
Identify levels with \textless{} 6 obs. & \(\times\) & \(\times\) &
\(\times\) & \(\times\) & & & & \\
Identify case issues & \(\times\) & \(\times\) & \(\times\) & \(\times\)
& & & & \\
Identify misclassified numeric or integer variables & \(\times\) &
\(\times\) & \(\times\) & \(\times\) & & & & \\
Identify outliers & & & & & \(\times\) & \(\times\) & & \(\times\) \\
\bottomrule()
\end{longtable}

Please note that all numerical values in the following have been rounded
to 2 decimals.

\hypertarget{summary-table}{%
\chapter{Summary table}\label{summary-table}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2600}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1700}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1800}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2300}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1600}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
~
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Variable class
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
\# unique values
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Missing observations
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Any problems?
\end{minipage} \\
\midrule()
\endhead
\protect\hyperlink{cod_setor}{Cod\_setor} & numeric & 32564 & 0.00 \%
& \\
\protect\hyperlink{cod_municipio}{Cod\_municipio} & numeric & 853 & 0.00
\% & \\
\protect\hyperlink{nome_do_municipio}{Nome\_do\_municipio} & character &
853 & 0.00 \% & \(\times\) \\
\protect\hyperlink{cod_bairro}{Cod\_bairro} & numeric & 2517 & 0.00 \%
& \\
\protect\hyperlink{nome_do_bairro}{Nome\_do\_bairro} & character & 2095
& 0.00 \% & \(\times\) \\
\protect\hyperlink{cod_subdistrito}{Cod\_subdistrito} & numeric & 1767 &
0.00 \% & \\
\protect\hyperlink{nome_do_subdistrito}{Nome\_do\_subdistrito} &
character & 1746 & 0.00 \% & \(\times\) \\
\protect\hyperlink{situacao_setor}{Situacao\_setor} & numeric & 8 & 0.00
\% & \\
\protect\hyperlink{v001}{V001} & numeric & 1611 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v002}{V002} & character & 1598 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v003}{V003} & character & 1547 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v004}{V004} & character & 327 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v005}{V005} & character & 856 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v006}{V006} & character & 1244 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v007}{V007} & character & 585 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v008}{V008} & character & 503 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v009}{V009} & character & 378 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v010}{V010} & character & 301 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v011}{V011} & character & 161 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v012}{V012} & character & 1573 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v013}{V013} & character & 673 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v014}{V014} & character & 180 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v015}{V015} & character & 661 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v016}{V016} & character & 1593 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v017}{V017} & character & 1510 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v018}{V018} & character & 602 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v019}{V019} & character & 1064 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v020}{V020} & character & 315 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v021}{V021} & character & 604 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v022}{V022} & character & 242 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v023}{V023} & character & 388 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v024}{V024} & character & 1587 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v025}{V025} & character & 1316 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v026}{V026} & character & 584 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v027}{V027} & character & 465 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v028}{V028} & character & 360 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v029}{V029} & character & 508 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v030}{V030} & character & 1571 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v031}{V031} & character & 1558 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v032}{V032} & character & 731 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v033}{V033} & character & 856 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v034}{V034} & character & 108 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v035}{V035} & character & 273 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v036}{V036} & character & 55 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v037}{V037} & character & 175 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v038}{V038} & character & 1601 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v039}{V039} & character & 1592 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v040}{V040} & character & 158 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v041}{V041} & character & 205 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v042}{V042} & character & 1507 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v043}{V043} & character & 399 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v044}{V044} & character & 362 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v045}{V045} & numeric & 872 & 0.00 \% & \(\times\) \\
\protect\hyperlink{v046}{V046} & character & 855 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v047}{V047} & character & 842 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v048}{V048} & character & 239 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v049}{V049} & character & 459 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v050}{V050} & character & 664 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v051}{V051} & character & 360 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v052}{V052} & character & 277 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v053}{V053} & character & 229 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v054}{V054} & character & 179 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v055}{V055} & character & 115 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v056}{V056} & character & 846 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v057}{V057} & character & 396 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v058}{V058} & character & 120 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v059}{V059} & character & 411 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v060}{V060} & character & 866 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v061}{V061} & character & 810 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v062}{V062} & character & 370 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v063}{V063} & character & 603 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v064}{V064} & character & 194 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v065}{V065} & character & 355 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v066}{V066} & character & 170 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v067}{V067} & character & 245 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v068}{V068} & character & 845 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v069}{V069} & character & 718 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v070}{V070} & character & 321 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v071}{V071} & character & 249 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v072}{V072} & character & 218 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v073}{V073} & character & 315 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v074}{V074} & character & 853 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v075}{V075} & character & 840 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v076}{V076} & character & 454 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v077}{V077} & character & 494 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v078}{V078} & character & 67 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v079}{V079} & character & 173 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v080}{V080} & character & 36 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v081}{V081} & character & 114 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v082}{V082} & character & 862 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v083}{V083} & character & 856 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v084}{V084} & character & 112 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v085}{V085} & character & 138 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v086}{V086} & character & 813 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v087}{V087} & character & 237 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v088}{V088} & character & 233 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v089}{V089} & numeric & 888 & 0.00 \% & \(\times\) \\
\protect\hyperlink{v090}{V090} & character & 888 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v091}{V091} & character & 856 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v092}{V092} & character & 253 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v093}{V093} & character & 526 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v094}{V094} & character & 686 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v095}{V095} & character & 380 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v096}{V096} & character & 282 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v097}{V097} & character & 203 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v098}{V098} & character & 187 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v099}{V099} & character & 107 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v100}{V100} & character & 875 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v101}{V101} & character & 362 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v102}{V102} & character & 109 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v103}{V103} & character & 380 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v104}{V104} & character & 888 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v105}{V105} & character & 837 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v106}{V106} & character & 365 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v107}{V107} & character & 607 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v108}{V108} & character & 191 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v109}{V109} & character & 353 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v110}{V110} & character & 161 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v111}{V111} & character & 224 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v112}{V112} & character & 881 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v113}{V113} & character & 730 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v114}{V114} & character & 341 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v115}{V115} & character & 285 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v116}{V116} & character & 234 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v117}{V117} & character & 301 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v118}{V118} & character & 872 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v119}{V119} & character & 863 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v120}{V120} & character & 466 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v121}{V121} & character & 461 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v122}{V122} & character & 63 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v123}{V123} & character & 176 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v124}{V124} & character & 37 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v125}{V125} & character & 102 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v126}{V126} & character & 874 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v127}{V127} & character & 877 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v128}{V128} & character & 115 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v129}{V129} & character & 120 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v130}{V130} & character & 831 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v131}{V131} & character & 218 & 0.00 \% &
\(\times\) \\
\protect\hyperlink{v132}{V132} & character & 225 & 0.00 \% &
\(\times\) \\
\bottomrule()
\end{longtable}

\hypertarget{variable-list}{%
\chapter{Variable list}\label{variable-list}}

\hypertarget{cod_setor}{%
\section{Cod\_setor}\label{cod_setor}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.4861}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 32564 \\
Median & 313380805000046 \\
1st and 3rd quartiles & 311200005000030; 315210505062544 \\
Min. and max. & 310010405000001; 317220210000002 \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-1-Cod-setor-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{cod_municipio}{%
\section{Cod\_municipio}\label{cod_municipio}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2639}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 853 \\
Median & 3133808 \\
1st and 3rd quartiles & 3112000; 3152105 \\
Min. and max. & 3100104; 3172202 \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-2-Cod-municipio-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{nome_do_municipio}{%
\section{Nome\_do\_municipio}\label{nome_do_municipio}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2639}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 853 \\
Mode & ``BELO HORIZONTE'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-3-Nome-do-municipio-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "ALBERTINA", "ANTÔNIO PRADO DE MINAS", "CARMÉSIA", "CASA GRANDE",
  "CASCALHO RICO", \ldots, "SERITINGA", "SERRA DA SAUDADE", "SERRANOS",
  "SILVEIRÂNIA", "WENCESLAU BRAZ" (28 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{cod_bairro}{%
\section{Cod\_bairro}\label{cod_bairro}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 2517 \\
Median & 3133808011.5 \\
1st and 3rd quartiles & 3.112e+09; 3152105024 \\
Min. and max. & 3100104000; 3172202000 \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-4-Cod-bairro-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{nome_do_bairro}{%
\section{Nome\_do\_bairro}\label{nome_do_bairro}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.4444}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 2095 \\
Mode & ``CONTAGEM (todos os setores)'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-5-Nome-do-bairro-1.pdf}

\end{minipage}

\begin{itemize}
\item
  Note that the following levels have at most five observations: "Aarão
  Reis", "Abaetezinho", "Abner Afonso", "Abolição", "Acaba Mundo",
  \ldots, "Xodo-Marize", "Zacarias Cimini", "Zarur", "Zilah Sposito",
  "Zona Central" (838 values omitted).
\item
  Note that there might be case problems with the following levels:
  "Morada do vale", "Morada do Vale".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{cod_subdistrito}{%
\section{Cod\_subdistrito}\label{cod_subdistrito}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.4167}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1767 \\
Median & 31338080500 \\
1st and 3rd quartiles & 31120000500; 31521050506.25 \\
Min. and max. & 31001040500; 31722021000 \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-6-Cod-subdistrito-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{nome_do_subdistrito}{%
\section{Nome\_do\_subdistrito}\label{nome_do_subdistrito}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1746 \\
Mode & ``UBERLÂNDIA'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-7-Nome-do-subdistrito-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations: "ABAETÉ
  DOS MENDES", "ABAETÉ DOS VENÂNCIOS", "ABAÍBA", "ABREUS", "ACURUÍ",
  \ldots, "VITORINOS", "VM5", "WENCESLAU BRAZ", "ZELÂNDIA", "ZITO
  SOARES" (666 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{situacao_setor}{%
\section{Situacao\_setor}\label{situacao_setor}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 8 \\
Median & 1 \\
1st and 3rd quartiles & 1; 3 \\
Min. and max. & 1; 8 \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-8-Situacao-setor-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v001}{%
\section{V001}\label{v001}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1528}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1611 \\
Median & 597 \\
1st and 3rd quartiles & 379; 805 \\
Min. and max. & 1; 3104 \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-9-V001-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "1424",
  "1425", "1426", "1428", "1429", \ldots, "2467", "2532", "2570",
  "2583", "3104" (193 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v002}{%
\section{V002}\label{v002}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1598 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-10-V002-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "888", "9", "99", "999".
\item
  Note that the following levels have at most five observations: "10",
  "11", "1107", "1113", "1114", \ldots, "2583", "3104", "7", "8", "9"
  (391 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v003}{%
\section{V003}\label{v003}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1547 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-11-V003-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "888", "9", "99", "999".
\item
  Note that the following levels have at most five observations: "1107",
  "1108", "1112", "1113", "1114", \ldots, "2446", "2523", "2558",
  "2560", "3099" (348 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v004}{%
\section{V004}\label{v004}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 327 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-12-V004-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "888", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "1007", "1009", "101", "102", \ldots, "958", "97", "98", "989", "99"
  (253 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v005}{%
\section{V005}\label{v005}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 856 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-13-V005-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1006",
  "1015", "1018", "1019", "1026", \ldots, "975", "977", "983", "986",
  "987" (476 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v006}{%
\section{V006}\label{v006}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1244 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-14-V006-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "888", "9", "99".
\item
  Note that the following levels have at most five observations: "1001",
  "1002", "1003", "1004", "1005", \ldots, "993", "994", "995", "996",
  "997" (304 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v007}{%
\section{V007}\label{v007}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 585 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-15-V007-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1016",
  "1031", "1107", "1108", "1123", \ldots, "922", "927", "928", "944",
  "987" (346 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v008}{%
\section{V008}\label{v008}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 503 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-16-V008-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1082",
  "327", "336", "340", "346", \ldots, "604", "616", "643", "665", "731"
  (122 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v009}{%
\section{V009}\label{v009}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 378 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-17-V009-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1224",
  "153", "154", "160", "170", \ldots, "565", "640", "665", "678", "697"
  (158 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v010}{%
\section{V010}\label{v010}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 301 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-18-V010-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1008",
  "1461", "162", "167", "170", \ldots, "600", "614", "672", "827", "837"
  (113 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v011}{%
\section{V011}\label{v011}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 161 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-19-V011-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "9".
\item
  Note that the following levels have at most five observations: "100",
  "103", "104", "105", "109", \ldots, "93", "94", "96", "97", "98" (101
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v012}{%
\section{V012}\label{v012}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1573 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-20-V012-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "888", "9", "99", "999".
\item
  Note that the following levels have at most five observations: "1053",
  "1071", "1112", "1115", "1117", \ldots, "2565", "299", "302", "3099",
  "312" (372 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v013}{%
\section{V013}\label{v013}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 673 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-21-V013-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1715",
  "288", "312", "327", "337", \ldots, "935", "947", "980", "981", "997"
  (247 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v014}{%
\section{V014}\label{v014}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 180 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-22-V014-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "101", "102", "103", "104", \ldots, "92", "93", "96", "98", "99" (113
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v015}{%
\section{V015}\label{v015}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 661 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-23-V015-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1032",
  "1033", "1049", "1053", "1070", \ldots, "913", "928", "949", "963",
  "998" (352 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v016}{%
\section{V016}\label{v016}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1593 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-24-V016-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "888", "9", "99", "999".
\item
  Note that the following levels have at most five observations: "10",
  "1068", "11", "1107", "1112", \ldots, "2583", "3104", "7", "8", "9"
  (384 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v017}{%
\section{V017}\label{v017}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1510 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-25-V017-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "888", "9", "99", "999".
\item
  Note that the following levels have at most five observations: "1038",
  "1041", "1043", "1056", "1057", \ldots, "239", "2443", "2460", "2536",
  "3102" (365 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v018}{%
\section{V018}\label{v018}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 602 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-26-V018-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1013",
  "1018", "1039", "1055", "1084", \ldots, "966", "967", "970", "978",
  "986" (386 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v019}{%
\section{V019}\label{v019}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1064 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-27-V019-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99", "999".
\item
  Note that the following levels have at most five observations: "1000",
  "1001", "1002", "1004", "1005", \ldots, "992", "993", "994", "998",
  "999" (527 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v020}{%
\section{V020}\label{v020}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 315 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-28-V020-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "102",
  "104", "105", "108", "110", \ldots, "92", "931", "94", "95", "96" (189
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v021}{%
\section{V021}\label{v021}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 604 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-29-V021-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1032",
  "1050", "1058", "176", "187", \ldots, "918", "931", "942", "973",
  "996" (308 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v022}{%
\section{V022}\label{v022}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 242 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-30-V022-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "101", "102", "103", "104", \ldots, "95", "96", "97", "98", "99" (152
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v023}{%
\section{V023}\label{v023}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 388 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-31-V023-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "101", "102", "107", "111", \ldots, "783", "808", "853", "869", "96"
  (252 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v024}{%
\section{V024}\label{v024}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1587 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-32-V024-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "888", "9", "99", "999".
\item
  Note that the following levels have at most five observations: "1",
  "10", "1043", "1091", "11", \ldots, "3093", "4", "6", "8", "9" (387
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v025}{%
\section{V025}\label{v025}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1316 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-33-V025-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "888", "9", "99", "999".
\item
  Note that the following levels have at most five observations: "1000",
  "1002", "1003", "1004", "1008", \ldots, "991", "992", "995", "996",
  "997" (324 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v026}{%
\section{V026}\label{v026}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 584 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-34-V026-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1050",
  "1060", "366", "371", "379", \ldots, "886", "897", "921", "963", "975"
  (177 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v027}{%
\section{V027}\label{v027}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 465 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-35-V027-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "187",
  "206", "213", "215", "216", \ldots, "643", "646", "661", "725", "907"
  (220 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v028}{%
\section{V028}\label{v028}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 360 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-36-V028-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "108",
  "116", "121", "123", "125", \ldots, "772", "855", "882", "913", "946"
  (216 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v029}{%
\section{V029}\label{v029}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 508 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-37-V029-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1069",
  "111", "1121", "1150", "1205", \ldots, "853", "876", "884", "911",
  "913" (300 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v030}{%
\section{V030}\label{v030}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1571 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-38-V030-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "888", "9", "99", "999".
\item
  Note that the following levels have at most five observations: "1110",
  "1117", "1119", "1122", "1124", \ldots, "2446", "2461", "2559", "302",
  "3104" (373 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v031}{%
\section{V031}\label{v031}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1558 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-39-V031-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "888", "9", "99", "999".
\item
  Note that the following levels have at most five observations: "1004",
  "1048", "1115", "1117", "1131", \ldots, "2446", "2461", "2559",
  "3104", "349" (363 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v032}{%
\section{V032}\label{v032}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 731 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-40-V032-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99", "999".
\item
  Note that the following levels have at most five observations: "1000",
  "1002", "1003", "1012", "1031", \ldots, "989", "990", "995", "996",
  "999" (537 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v033}{%
\section{V033}\label{v033}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 856 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-41-V033-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1000",
  "1003", "1009", "1013", "1018", \ldots, "970", "971", "992", "994",
  "997" (359 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v034}{%
\section{V034}\label{v034}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 108 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-42-V034-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "107", "108", "110", "111", \ldots, "88", "92", "93", "94", "99" (46
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v035}{%
\section{V035}\label{v035}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 273 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-43-V035-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "102", "105", "107", "110", \ldots, "838", "900", "94", "955", "957"
  (151 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v036}{%
\section{V036}\label{v036}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 55 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-44-V036-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "9".
\item
  Note that the following levels have at most five observations: "118",
  "158", "17", "18", "19", \ldots, "77", "84", "87", "95", "96" (24
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v037}{%
\section{V037}\label{v037}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 175 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-45-V037-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9".
\item
  Note that the following levels have at most five observations: "100",
  "101", "102", "103", "104", \ldots, "89", "90", "95", "96", "98" (91
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v038}{%
\section{V038}\label{v038}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1601 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-46-V038-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "888", "9", "99", "999".
\item
  Note that the following levels have at most five observations: "1",
  "1112", "1118", "1137", "1146", \ldots, "5", "6", "7", "8", "9" (391
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v039}{%
\section{V039}\label{v039}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1592 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-47-V039-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "888", "9", "99", "999".
\item
  Note that the following levels have at most five observations: "1",
  "10", "11", "1137", "1146", \ldots, "5", "6", "7", "8", "9" (384
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v040}{%
\section{V040}\label{v040}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 158 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-48-V040-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "9".
\item
  Note that the following levels have at most five observations: "100",
  "103", "105", "106", "108", \ldots, "95", "957", "96", "97", "98" (107
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v041}{%
\section{V041}\label{v041}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 205 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-49-V041-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "101", "102", "103", "104", \ldots, "94", "96", "97", "98", "99" (116
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v042}{%
\section{V042}\label{v042}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1507 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-50-V042-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "888", "9", "99", "999".
\item
  Note that the following levels have at most five observations: "1",
  "1043", "1050", "1058", "1059", \ldots, "2418", "2429", "2460",
  "2891", "972" (353 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v043}{%
\section{V043}\label{v043}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 399 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-51-V043-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "188",
  "190", "195", "200", "203", \ldots, "606", "608", "704", "764", "845"
  (165 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v044}{%
\section{V044}\label{v044}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 362 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-52-V044-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "101",
  "103", "108", "111", "115", \ldots, "869", "927", "95", "951", "977"
  (227 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v045}{%
\section{V045}\label{v045}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1528}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 872 \\
Median & 292 \\
1st and 3rd quartiles & 189; 393 \\
Min. and max. & 0; 1799 \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-53-V045-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "707",
  "708", "709", "710", "711", \ldots, "1295", "1493", "1516", "1527",
  "1799" (156 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v046}{%
\section{V046}\label{v046}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 855 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-54-V046-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1003",
  "1005", "1008", "1041", "1066", \ldots, "980", "984", "985", "986",
  "989" (193 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v047}{%
\section{V047}\label{v047}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 842 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-55-V047-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99", "999".
\item
  Note that the following levels have at most five observations: "1031",
  "1052", "1069", "1076", "1077", \ldots, "976", "983", "987", "989",
  "999" (194 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v048}{%
\section{V048}\label{v048}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 239 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-56-V048-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "101", "102", "103", "105", \ldots, "95", "96", "97", "98", "99" (176
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v049}{%
\section{V049}\label{v049}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 459 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-57-V049-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "203",
  "212", "215", "226", "230", \ldots, "632", "668", "682", "703", "730"
  (183 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v050}{%
\section{V050}\label{v050}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 664 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-58-V050-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1069",
  "462", "490", "494", "505", \ldots, "832", "833", "840", "876", "886"
  (138 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v051}{%
\section{V051}\label{v051}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 360 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-59-V051-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "113",
  "1146", "119", "126", "131", \ldots, "715", "747", "857", "874", "936"
  (195 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v052}{%
\section{V052}\label{v052}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 277 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-60-V052-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "185",
  "189", "193", "198", "203", \ldots, "332", "337", "340", "388", "490"
  (62 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v053}{%
\section{V053}\label{v053}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 229 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-61-V053-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "120",
  "127", "131", "138", "139", \ldots, "322", "346", "369", "370", "712"
  (77 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v054}{%
\section{V054}\label{v054}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 179 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-62-V054-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "101", "102", "103", "104", \ldots, "370", "380", "471", "648", "99"
  (67 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v055}{%
\section{V055}\label{v055}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 115 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-63-V055-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "9".
\item
  Note that the following levels have at most five observations: "101",
  "102", "108", "112", "117", \ldots, "90", "92", "93", "94", "97" (69
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v056}{%
\section{V056}\label{v056}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 846 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-64-V056-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99", "999".
\item
  Note that the following levels have at most five observations: "1005",
  "1022", "1057", "1071", "1086", \ldots, "980", "986", "987", "989",
  "999" (193 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v057}{%
\section{V057}\label{v057}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 396 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-65-V057-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "233",
  "237", "245", "248", "249", \ldots, "487", "514", "518", "536", "985"
  (125 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v058}{%
\section{V058}\label{v058}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 120 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-66-V058-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "9", "99".
\item
  Note that the following levels have at most five observations: "104",
  "105", "107", "108", "111", \ldots, "93", "95", "96", "98", "99" (69
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v059}{%
\section{V059}\label{v059}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 411 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-67-V059-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "161",
  "171", "175", "176", "178", \ldots, "642", "649", "692", "714", "779"
  (196 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v060}{%
\section{V060}\label{v060}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 866 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-68-V060-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1003",
  "1005", "1007", "1041", "1066", \ldots, "978", "980", "984", "986",
  "988" (207 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v061}{%
\section{V061}\label{v061}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 810 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-69-V061-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1005",
  "1020", "1068", "1075", "1086", \ldots, "971", "977", "979", "980",
  "998" (191 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v062}{%
\section{V062}\label{v062}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 370 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-70-V062-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "118",
  "120", "124", "127", "129", \ldots, "559", "569", "584", "590", "855"
  (204 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v063}{%
\section{V063}\label{v063}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 603 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-71-V063-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1069",
  "272", "313", "317", "318", \ldots, "752", "757", "828", "895", "917"
  (231 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v064}{%
\section{V064}\label{v064}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 194 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-72-V064-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "101", "102", "104", "105", \ldots, "93", "94", "97", "98", "99" (97
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v065}{%
\section{V065}\label{v065}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 355 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-73-V065-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "152",
  "157", "166", "169", "171", \ldots, "489", "490", "503", "517", "519"
  (152 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v066}{%
\section{V066}\label{v066}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 170 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-74-V066-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "101", "102", "104", "105", \ldots, "94", "95", "96", "97", "99" (99
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v067}{%
\section{V067}\label{v067}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 245 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-75-V067-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "101",
  "103", "106", "107", "108", \ldots, "93", "96", "97", "98", "99" (132
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v068}{%
\section{V068}\label{v068}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 845 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-76-V068-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1",
  "1002", "1005", "1022", "1058", \ldots, "972", "980", "981", "984",
  "990" (198 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v069}{%
\section{V069}\label{v069}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 718 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-77-V069-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1007",
  "1019", "1040", "1050", "1085", \ldots, "918", "920", "926", "932",
  "963" (169 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v070}{%
\section{V070}\label{v070}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 321 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-78-V070-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "200",
  "204", "206", "210", "213", \ldots, "449", "453", "464", "478", "535"
  (96 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v071}{%
\section{V071}\label{v071}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 249 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-79-V071-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "131",
  "140", "143", "144", "145", \ldots, "303", "311", "323", "324", "408"
  (90 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v072}{%
\section{V072}\label{v072}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 218 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-80-V072-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "101",
  "102", "103", "105", "106", \ldots, "94", "96", "97", "98", "99" (119
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v073}{%
\section{V073}\label{v073}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 315 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-81-V073-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "107",
  "108", "116", "117", "118", \ldots, "488", "507", "589", "596", "601"
  (152 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v074}{%
\section{V074}\label{v074}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 853 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-82-V074-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99", "999".
\item
  Note that the following levels have at most five observations: "1005",
  "1037", "1047", "1066", "1071", \ldots, "978", "980", "984", "986",
  "999" (203 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v075}{%
\section{V075}\label{v075}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 840 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-83-V075-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99", "999".
\item
  Note that the following levels have at most five observations: "1005",
  "1037", "1042", "1066", "1071", \ldots, "978", "980", "984", "986",
  "999" (198 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v076}{%
\section{V076}\label{v076}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 454 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-84-V076-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1077",
  "112", "114", "116", "117", \ldots, "593", "595", "602", "689", "789"
  (278 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v077}{%
\section{V077}\label{v077}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 494 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-85-V077-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "248",
  "255", "262", "267", "283", \ldots, "659", "674", "680", "697", "717"
  (171 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v078}{%
\section{V078}\label{v078}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 67 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-86-V078-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "9".
\item
  Note that the following levels have at most five observations: "105",
  "117", "121", "122", "151", \ldots, "67", "70", "80", "82", "86" (19
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v079}{%
\section{V079}\label{v079}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 173 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-87-V079-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "101", "102", "103", "104", \ldots, "95", "96", "97", "98", "99" (87
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v080}{%
\section{V080}\label{v080}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 36 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-88-V080-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "9".
\item
  Note that the following levels have at most five observations: "11",
  "12", "13", "15", "17", \ldots, "50", "51", "61", "77", "89" (12
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v081}{%
\section{V081}\label{v081}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 114 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-89-V081-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "103", "104", "105", "107", \ldots, "91", "94", "97", "98", "99" (52
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v082}{%
\section{V082}\label{v082}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 862 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-90-V082-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1",
  "1003", "1005", "1006", "1034", \ldots, "975", "979", "980", "984",
  "986" (198 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v083}{%
\section{V083}\label{v083}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 856 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-91-V083-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1",
  "1003", "1005", "1006", "1034", \ldots, "979", "980", "982", "984",
  "986" (197 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v084}{%
\section{V084}\label{v084}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 112 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-92-V084-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9".
\item
  Note that the following levels have at most five observations: "100",
  "105", "107", "108", "111", \ldots, "93", "94", "95", "96", "97" (72
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v085}{%
\section{V085}\label{v085}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 138 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-93-V085-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "106", "107", "108", "109", \ldots, "93", "94", "95", "97", "99" (68
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v086}{%
\section{V086}\label{v086}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 813 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-94-V086-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1019",
  "1029", "1030", "1056", "1071", \ldots, "935", "936", "958", "978",
  "979" (189 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v087}{%
\section{V087}\label{v087}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 237 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-95-V087-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "130",
  "131", "134", "135", "138", \ldots, "318", "319", "334", "367", "453"
  (86 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v088}{%
\section{V088}\label{v088}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 233 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-96-V088-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "101", "103", "104", "105", \ldots, "94", "95", "97", "98", "99" (134
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v089}{%
\section{V089}\label{v089}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1528}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 888 \\
Median & 305 \\
1st and 3rd quartiles & 186; 414 \\
Min. and max. & 0; 1588 \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-97-V089-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "729",
  "730", "731", "732", "733", \ldots, "1236", "1294", "1303", "1309",
  "1588" (149 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v090}{%
\section{V090}\label{v090}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 888 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-98-V090-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "888", "9", "99".
\item
  Note that the following levels have at most five observations: "1",
  "1016", "1019", "1039", "1040", \ldots, "980", "983", "991", "994",
  "997" (204 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v091}{%
\section{V091}\label{v091}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 856 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-99-V091-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1008",
  "1013", "1038", "1040", "1052", \ldots, "974", "978", "989", "992",
  "997" (198 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v092}{%
\section{V092}\label{v092}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 253 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-100-V092-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9".
\item
  Note that the following levels have at most five observations: "100",
  "101", "102", "103", "104", \ldots, "93", "94", "95", "96", "97" (191
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v093}{%
\section{V093}\label{v093}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 526 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-101-V093-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "210",
  "216", "219", "223", "241", \ldots, "694", "740", "752", "769", "794"
  (215 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v094}{%
\section{V094}\label{v094}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 686 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-102-V094-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1132",
  "500", "501", "503", "506", \ldots, "814", "824", "834", "936", "960"
  (153 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v095}{%
\section{V095}\label{v095}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 380 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-103-V095-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1005",
  "1166", "140", "141", "146", \ldots, "708", "795", "802", "805", "889"
  (203 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v096}{%
\section{V096}\label{v096}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 282 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-104-V096-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "204",
  "206", "208", "209", "211", \ldots, "316", "317", "325", "343", "592"
  (58 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v097}{%
\section{V097}\label{v097}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 203 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-105-V097-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "104",
  "117", "118", "125", "127", \ldots, "309", "318", "319", "327", "512"
  (63 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v098}{%
\section{V098}\label{v098}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 187 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-106-V098-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "102",
  "104", "105", "107", "108", \ldots, "467", "537", "813", "96", "98"
  (72 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v099}{%
\section{V099}\label{v099}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 107 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-107-V099-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "105", "106", "109", "118", \ldots, "89", "91", "92", "97", "99" (62
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v100}{%
\section{V100}\label{v100}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 875 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-108-V100-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1016",
  "1024", "1038", "1048", "1052", \ldots, "980", "983", "991", "994",
  "997" (197 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v101}{%
\section{V101}\label{v101}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 362 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-109-V101-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "202",
  "203", "209", "217", "221", \ldots, "450", "461", "467", "510", "730"
  (112 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v102}{%
\section{V102}\label{v102}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 109 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-110-V102-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9".
\item
  Note that the following levels have at most five observations: "100",
  "101", "108", "109", "114", \ldots, "91", "92", "95", "96", "97" (59
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v103}{%
\section{V103}\label{v103}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 380 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-111-V103-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "147",
  "158", "159", "168", "178", \ldots, "629", "634", "644", "682", "724"
  (179 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v104}{%
\section{V104}\label{v104}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 888 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-112-V104-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "888", "9", "99".
\item
  Note that the following levels have at most five observations: "1",
  "1011", "1016", "1027", "1039", \ldots, "980", "983", "991", "994",
  "997" (208 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v105}{%
\section{V105}\label{v105}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 837 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-113-V105-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1034",
  "1047", "1050", "1069", "1077", \ldots, "982", "983", "987", "990",
  "991" (187 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v106}{%
\section{V106}\label{v106}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 365 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-114-V106-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "106",
  "112", "120", "128", "139", \ldots, "593", "610", "624", "630", "74"
  (204 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v107}{%
\section{V107}\label{v107}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 607 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-115-V107-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1142",
  "268", "293", "300", "303", \ldots, "738", "740", "799", "855", "866"
  (242 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v108}{%
\section{V108}\label{v108}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 191 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-116-V108-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "101",
  "102", "103", "105", "106", \ldots, "94", "95", "96", "97", "98" (101
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v109}{%
\section{V109}\label{v109}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 353 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-117-V109-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "135",
  "156", "159", "165", "167", \ldots, "493", "498", "513", "541", "547"
  (151 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v110}{%
\section{V110}\label{v110}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 161 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-118-V110-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "102", "103", "104", "106", \ldots, "94", "95", "96", "98", "99" (89
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v111}{%
\section{V111}\label{v111}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 224 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-119-V111-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "101", "103", "104", "105", \ldots, "93", "94", "96", "98", "99" (121
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v112}{%
\section{V112}\label{v112}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 881 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-120-V112-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1",
  "1011", "1036", "1053", "1054", \ldots, "980", "983", "989", "991",
  "994" (202 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v113}{%
\section{V113}\label{v113}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 730 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-121-V113-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1018",
  "1043", "1091", "1101", "1107", \ldots, "928", "935", "947", "968",
  "971" (174 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v114}{%
\section{V114}\label{v114}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 341 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-122-V114-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "211",
  "220", "224", "225", "226", \ldots, "475", "497", "499", "515", "525"
  (101 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v115}{%
\section{V115}\label{v115}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 285 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-123-V115-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "118",
  "144", "146", "150", "151", \ldots, "350", "351", "354", "402", "499"
  (116 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v116}{%
\section{V116}\label{v116}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 234 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-124-V116-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "101", "103", "105", "106", \ldots, "92", "93", "94", "96", "98" (134
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v117}{%
\section{V117}\label{v117}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 301 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-125-V117-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "113",
  "115", "124", "125", "127", \ldots, "561", "562", "609", "91", "93"
  (146 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v118}{%
\section{V118}\label{v118}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 872 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-126-V118-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "888", "9", "99".
\item
  Note that the following levels have at most five observations: "1015",
  "1016", "1031", "1048", "1053", \ldots, "980", "983", "991", "994",
  "997" (194 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v119}{%
\section{V119}\label{v119}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 863 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-127-V119-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "888", "9", "99".
\item
  Note that the following levels have at most five observations: "1016",
  "1031", "1048", "1051", "1053", \ldots, "980", "983", "989", "994",
  "997" (195 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v120}{%
\section{V120}\label{v120}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 466 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-128-V120-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "102",
  "1048", "107", "118", "119", \ldots, "590", "604", "610", "674", "695"
  (298 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v121}{%
\section{V121}\label{v121}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 461 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-129-V121-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "227",
  "245", "249", "255", "260", \ldots, "639", "640", "641", "647", "713"
  (159 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v122}{%
\section{V122}\label{v122}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 63 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-130-V122-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "9".
\item
  Note that the following levels have at most five observations: "102",
  "104", "29", "33", "35", \ldots, "70", "82", "95", "96", "97" (19
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v123}{%
\section{V123}\label{v123}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 176 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-131-V123-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "101", "102", "103", "104", \ldots, "95", "96", "97", "98", "99" (99
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v124}{%
\section{V124}\label{v124}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 37 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-132-V124-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "9".
\item
  Note that the following levels have at most five observations: "105",
  "14", "15", "16", "17", \ldots, "44", "46", "47", "57", "81" (12
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v125}{%
\section{V125}\label{v125}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 102 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-133-V125-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "110",
  "114", "115", "119", "120", \ldots, "91", "92", "93", "94", "99" (46
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v126}{%
\section{V126}\label{v126}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 874 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-134-V126-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "888", "9", "99".
\item
  Note that the following levels have at most five observations: "1",
  "1016", "1019", "1034", "1037", \ldots, "980", "983", "990", "994",
  "997" (192 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v127}{%
\section{V127}\label{v127}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 877 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-135-V127-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "888", "9", "99".
\item
  Note that the following levels have at most five observations: "1",
  "1016", "1017", "1032", "1037", \ldots, "980", "983", "990", "993",
  "997" (190 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v128}{%
\section{V128}\label{v128}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 115 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-136-V128-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "101", "104", "107", "108", \ldots, "89", "94", "95", "96", "99" (77
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v129}{%
\section{V129}\label{v129}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 120 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-137-V129-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "100",
  "101", "103", "104", "108", \ldots, "91", "93", "95", "97", "99" (57
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v130}{%
\section{V130}\label{v130}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 831 \\
Mode & ``X'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-138-V130-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "1007",
  "1016", "1020", "1025", "1039", \ldots, "950", "961", "970", "983",
  "993" (182 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v131}{%
\section{V131}\label{v131}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 218 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-139-V131-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "109",
  "113", "127", "129", "131", \ldots, "299", "306", "370", "392", "397"
  (75 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{v132}{%
\section{V132}\label{v132}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule()
\endhead
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 225 \\
Mode & ``0'' \\
\bottomrule()
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_df_files/figure-latex/Var-140-V132-1.pdf}

\end{minipage}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8", "88", "9", "99".
\item
  Note that the following levels have at most five observations: "101",
  "102", "103", "104", "105", \ldots, "95", "96", "97", "98", "99" (128
  values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

Report generation information:

\begin{itemize}
\item
  Created by: Caio Gonçalves (username: \texttt{Caio}).
\item
  Report creation time: qua ago 23 2023 01:46:26
\item
  Report was run from directory:
  \texttt{C:/Users/Caio/Documents/GitHub/mqagp}
\item
  dataMaid v1.4.1 {[}Pkg: 2021-10-08 from CRAN (R 4.2.3){]}
\item
  R version 4.2.1 (2022-06-23 ucrt).
\item
  Platform: x86\_64-w64-mingw32/x64 (64-bit)(Windows 10 x64 (build
  19045)).
\item
  Function call: \texttt{makeDataReport(data\ =\ df,\ replace\ =\ TRUE)}
\end{itemize}

\end{document}
